### ISSUE TITLE
Avoid calling "chart.draw()" twice in control callbacks

### ISSUE THREAD

**Issue by jwildfire** [ASA-DIA-InteractiveSafetyGraphics/safety-eDISH#123]
The custom callback from  config.display and config.cuts controls are both calling chart.draw() twice. 

Would be nice to update webcharts to have the option to supress this behaviour, something like a "control.draw=false" option that enables the user to supress the standard chart.draw() call after a control is changed.

**Comment by jwildfire** [comment]
Submitted [PR in webcharts](https://github.com/RhoInc/Webcharts/pull/216). Almost certainly easiest to hold off on this until that is released instead of doing a major refactor here. 

Once that release is live, we just need to add `draw=false` to the relevant controls as described above.

**Comment by samussiah** [comment]
The reason the chart is drawing twice is it's drawing once from the Webcharts controls' event listener on `select.changer` and again from any custom `change` event listeners on `div.control-group`.  You can overwrite Webcharts controls' event listeners by defining a new `change` event listener on the `select.changer` rather than the `div.control-group`.  Still, the Webcharts issue is a good idea to avoid extraneous event listeners that will be overwritten anyway.

**Comment by jwildfire** [comment]
Good idea on the quick fix. Lets do it in to v0.12.1
