### ISSUE TITLE
Remove raw data cutoff values

### ISSUE THREAD

**Issue by zskrivan** [ASA-DIA-InteractiveSafetyGraphics/safety-eDISH#132]
When we switch scales we still want to use the same  relative cutoffs.  The default cutoff for raw data for ALT and TB should be 3xULN (ALT) and 2xULN (TB) for ALT and TB, respectively.

**Comment by jwildfire** [comment]
I see where you're coming from, but I'm not sure it's feasible. The upper limit of normal can change from person to person, which would lead to multiple reference lines on a single chart when viewing the data in the raw units (which is definitely not supported right now). The only options I see are: 
- Figure out a single cut point for each measure using the raw units
- Disable cut points altogether when viewing the raw units

@JimBuchanan do you have any guidance on this front?

**Comment by JimBuchanan** [comment]
Jeremy,

I’m not sure what the question is. The upper limit of normal doesn’t change between people but possibly between labs. That said, most studies either use a central lab where there is no difference, or sometime local labs where there could be different ranges (although not by a great deal). The alternative is to use the mDISH which changes the variable to the fold change from individual baseline.

Let me know if I’ve missed something.

Thanks,

Jim

**Comment by jwildfire** [comment]
I guess the bottom line is that, users can definitely load data where the ULN differs between records. Accordingly, using a data-driven approach to setting the cutpoints for raw units (e.g. multiplying the ULN x cutpoint for eDish) is dependent on the loaded data, and would require some careful thought to implement. 

I think a simpler approach is to say: "The default cut point is X for measure Y" and let the user change it with the interactive controls as desired.  If we take that approach, we just need to know default cut points for all of the standard measures: TB, ALT, AST, ALP.

**Comment by JimBuchanan** [comment]
Jeremy,

Predefining the upper limits for some of these can be difficult as they vary between laboratories. For example, the upper limit of ALT can range from 30 to 55 U/L. The expectation in the dataset would be the inclusion of the reference range for each analyte result. Where it gets difficult is when the dataset includes data from different laboratories. In that case the user would have to figure out what to use: the lower of the range of limits, the upper of the range of limits, an average. Or if there is a great variety of labs being used (use of “local” labs instead of “central” labs), then the user would just have to pick an upper limit they feel comfortable with.

Thanks,

Jim

**Comment by jwildfire** [comment]
Marking this 'won't fix' and closing since the group decided to remove the "raw data" display option in the eDish plot from the standard workflow and put it in the longitudinal participant plot instead (see #139). With that decision, we don't need to worry about defining global cut-points for raw values at this time. A separate issue (#140) has been created to add a new control that allows users to create a population-wide ULN value instead of using the data driven cuts.
