### ISSUE TITLE
Add option to view AST on the x-axis. 

### ISSUE THREAD

**Issue by jwildfire** [ASA-DIA-InteractiveSafetyGraphics/safety-eDISH#48]
## Clinical Summary

Add a toggle that allows the user to change the variable shown on the x-axis. Hy's law typically incorporates both AST and ALT vs TB.

**Comment by JimBuchanan** [comment]
This would be an important feature to include in v1.0.

**Comment by samussiah** [comment]
Does AST have the same threshold values as ALT (xULN: 3, xBaseline: 3.8, absolute: 1)?

**Comment by JimBuchanan** [comment]
Yes, for fold change from baseline AST has the same threshold as ALT: 3x ULN. The multivariate outlier detection method that established the 3.8 x baseline value for ALT only considered ALT. However, since we use the same boundary for ALT and AST for the gold change from ULN, it is not unreasonable to also use the 3.8 x baseline threshold for AST as for ALT.

Thanks

Jim


Sent from my iPhone

On Jul 30, 2018, at 7:06 PM, Spencer Childress <notifications@github.com<mailto:notifications@github.com>> wrote:


Does AST have the same threshold values as ALT (xULN: 3, xBaseline: 3.8, absolute: 1)?
