### ISSUE TITLE
Add linked plot for longitudinal lab values on click

### ISSUE THREAD

**Issue by jwildfire** [ASA-DIA-InteractiveSafetyGraphics/safety-eDISH#71]
## Clinical Summary

Show relevant lab values over time using common axes (xULN) when a participant point is clicked. 

## Details
Quick prototype implemented [here](https://rawgit.com/ASA-DIA-InteractiveSafetyGraphics/safety-eDISH/82a7a3173b78518affdf1f710d7de8b82342eea3/test/) and screenshot pasted below. Suggestions on implementation details, additional features and formatting is welcome! 

![screen shot 2018-06-19 at 7 58 41 am](https://user-images.githubusercontent.com/3680095/41676553-c177062e-747a-11e8-8dc5-92c4a8615b59.png)

**Comment by JimBuchanan** [comment]
For analytes to include in the longitudinal plot, I would recommend ALT, AST, bilirubin, alkaline phosphatase and GGT (gamma glutamyl-transferase). The AST is the complementary transaminase of interest when ALT is elevated.  Some eDISH plots graph AST vs bilirubin in place of ALT (perhaps we can add a user toggle to switch between ALT and AST in the graph). The relative increases in ALT vs AST can speak to the underlying mechanism. Alkaline phophatase elevation is important to identify as it can signal a cholestatic process rather than a hepatotoxic one. However, alkaline phosphatase is elevated in many cancers that metastasize to the bone, making it less useful when eDISH is performed in an oncology population. In that circumstance we can use GGT as a second approximation of cholestatic mechanisms.

**Comment by JimBuchanan** [comment]
Jeremy,

I went through each of the open clinical issues and added a comment.

Thanks,

Jim
