### ISSUE TITLE
Add an annotation of the baseline visit for mDish

### ISSUE THREAD

**Issue by jwildfire** [ASA-DIA-InteractiveSafetyGraphics/safety-eDISH#77]
## Feature Summary

When viewing baseline adjusted data (aka mDish), add a footnote to indicate which timepoint is being used for baseline.

**Comment by JimBuchanan** [comment]
How would this be implemented? Depending on the study design, this could be from a screening lab test, a baseline lab or on Day 1 prior to first dosing (which could be defined as "baseline" depending on the protocol).

**Comment by jwildfire** [comment]
@JimBuchanan Right now, the baseline time point is defined using the [`baseline_visitn`](https://github.com/ASA-DIA-InteractiveSafetyGraphics/safety-eDISH/wiki/Configuration#settingsbaseline_visitn) setting, and must be a single numeric value. So the annotation would just be something simple like, "Baseline is defined as Visit 1" 

Perhaps we should create a separate issue to discuss refactoring/expanding the ways baseline is defined? We've discussed this a bit in the past, and I think there are several approaches we could consider.

**Comment by JimBuchanan** [comment]
That makes sense. This is where we’ll need some user defined input since it could represent one of several pre-dose tome points depending on study design.

Thanks

Jim

Sent from my iPhone

On Jul 16, 2018, at 10:05 PM, jwildfire <notifications@github.com<mailto:notifications@github.com>> wrote:


@JimBuchanan<https://github.com/JimBuchanan> Right now, the baseline time point is defined using the baseline_visitn<https://github.com/ASA-DIA-InteractiveSafetyGraphics/safety-eDISH/wiki/Configuration#settingsbaseline_visitn> setting, and must be a single numeric value. So the annotation would just be something simple like, "Baseline is defined as Visit 1"

Perhaps we should create a separate issue to discuss refactoring/expanding the ways baseline is defined? We've discussed this a bit in the past, and I think there are several approaches we could consider.

**Comment by 31leen** [comment]
I agree that the single test value identified at baseline can serve as the default for V1. A toggle that allows a choice for the maximum pre-treatment value as baseline may find utility for more complex submissions.
